'use strict';

// Tab
export const TAB_BUS = 'TAB_BUS';
export const TAB_FILE = 'TAB_FILE';
export const TAB_MAP = 'TAB_MAP';
export const TAB_NEWS = 'TAB_NEWS';
export const TAB_SETTING = 'TAB_SETTING';

// Map
export const CHANGE_MAP_CAMPUS = 'CHANGE_MAP_CAMPUS';

// News
export const NEWS_LIST_REQUEST = 'NEWS_LIST_REQUEST';
export const NEWS_LIST_SUCCESS = 'NEWS_LIST_SUCCESS';
export const NEWS_LIST_FAILURE = 'NEWS_LIST_FAILURE';

export const SINGLE_NEWS_REQUEST = 'SINGLE_NEWS_REQUEST';
export const SINGLE_NEWS_SUCCESS = 'SINGLE_NEWS_SUCCESS';
export const SINGLE_NEWS_FAILURE = 'SINGLE_NEWS_FAILURE';

export const CHANGE_NEWS_CATEGORY = 'CHANGE_NEWS_CATEGORY';
export const SHOULD_NOT_SHOW_SINGLE_NEWS = 'SHOULD_NOT_SHOW_SINGLE_NEWS';

// File
export const FILE_CODE_ADD_REQUEST = 'FILE_CODE_ADD_REQUEST';
export const FILE_CODE_ADD_SUCCESS = 'FILE_CODE_ADD_SUCCESS';
export const FILE_CODE_ADD_FAILURE = 'FILE_CODE_ADD_FAILURE';

export const FILE_CODE_LIST_REQUEST = 'FILE_CODE_LIST_REQUEST';
export const FILE_CODE_LIST_SUCCESS = 'FILE_CODE_LIST_SUCCESS';
export const FILE_CODE_LIST_FAILURE = 'FILE_CODE_LIST_FAILURE';

export const FILE_CODE_SINGLE_REQUEST = 'FILE_CODE_SINGLE_REQUEST';
export const FILE_CODE_SINGLE_SUCCESS = 'FILE_CODE_SINGLE_SUCCESS';
export const FILE_CODE_SINGLE_FAILURE = 'FILE_CODE_SINGLE_FAILURE';